import 'package:drift/drift.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:uuid/uuid.dart';

import 'app_database.dart';
import 'generated/muscle_taxonomy.dart';
import 'settings_store.dart' show appDatabaseProvider;
import 'workout_templates.dart';

/// Reads and writes the templates the user built for themselves.
///
/// **A store rather than handing the database to UI code**, matching
/// [SettingsStore] and `PersonalDetailsStore`: widgets ask for templates, they
/// do not learn drift's query API, and swapping the storage underneath them
/// stays a change to this file.
///
/// **It deals in the columns, not in [WorkoutTemplate].** The group ids come
/// back as the stored comma-joined string and go in the same way. Deciding what
/// that string means — which ids the taxonomy still knows, what order they
/// render in — belongs to [encodeGroupIds] and [decodeGroupIds] below, which
/// own that vocabulary, exactly as [SettingsStore] leaves the filter keys to
/// the filter provider.
///
/// **Unlike the bodyweight series, these rows are fully mutable.** A bodyweight
/// entry is immutable because the calorie estimate is derived from the weight
/// *in effect on* a session's date, so editing one silently re-prices logged
/// history. A template is the opposite: nothing derives a past session's
/// contents from it, because a session records the exercises that were actually
/// performed. Renaming and deleting are therefore safe, and are the whole point
/// — a user duplicates an immutable predefined template precisely to get a copy
/// they can change (`docs/00-build-spec.md` §11).
class CustomTemplateStore {
  const CustomTemplateStore(this._db);

  final AppDatabase _db;

  /// Every custom template, in name order.
  ///
  /// **Ordered by name because there is nothing else to order by.** The table
  /// has no insertion-order column and this unit must not add one — so the only
  /// stable, meaningful order available is the one the user themselves typed.
  /// Sorting in the caller would be worse than it looks: the order after a
  /// write has to match the order the next launch reads back, or the list
  /// quietly reshuffles on restart, and keeping that one fact here is what
  /// [CustomTemplateList] copies rather than re-derives.
  ///
  /// [id] breaks the tie, so duplicating one template twice does not leave the
  /// pair swapping places between launches.
  ///
  /// The whole table is read at once because it is a handful of short rows and
  /// the landing renders all of them.
  Future<List<CustomTemplateRow>> readCustomTemplates() {
    return (_db.select(_db.customTemplates)
          ..orderBy(<OrderingTerm Function($CustomTemplatesTable)>[
            (t) => OrderingTerm.asc(t.name),
            (t) => OrderingTerm.asc(t.id),
          ]))
        .get();
  }

  /// Saves a new template.
  ///
  /// **An upsert against [id], and [id] is generated by the caller.** Re-saving
  /// an id that already exists replaces that template rather than failing — the
  /// alternative, a plain insert, would throw on the one path a retry could
  /// ever take. [sourceTemplateId] is null for a template the user built from
  /// scratch, which is a real answer and not a missing one: it is how that is
  /// told apart from a duplicate of a predefined template that no longer ships.
  Future<void> insertCustomTemplate({
    required String id,
    required String name,
    required String groupIds,
    String? sourceTemplateId,
  }) async {
    await _db.into(_db.customTemplates).insertOnConflictUpdate(
          CustomTemplatesCompanion.insert(
            id: id,
            name: name,
            groupIds: groupIds,
            sourceTemplateId: Value<String?>(sourceTemplateId),
          ),
        );
  }

  /// Renames the template with [id]. A stale id writes nothing.
  ///
  /// **A partial companion write, not a read-modify-write.** An
  /// [UpdateCompanion] carries only the columns it was given, so this leaves
  /// `groupIds` and `sourceTemplateId` exactly as they were. Rebuilding the
  /// whole row from a read would blank whichever column the caller forgot, and
  /// nothing would fail — the same trap `PersonalDetailsStore.writeBodyGender`
  /// documents for the shared settings row.
  Future<void> renameCustomTemplate(String id, String name) async {
    await (_db.update(_db.customTemplates)..where((t) => t.id.equals(id)))
        .write(CustomTemplatesCompanion(name: Value<String>(name)));
  }

  /// Deletes the template with [id]. A stale id deletes nothing.
  ///
  /// **A real delete, and `CLAUDE.md` is explicit that V1 has no soft delete.**
  /// Nothing derives from a template once it has been used — a session records
  /// the exercises performed, not a pointer to the menu they were browsed from
  /// — so there is no history to keep the row alive for.
  Future<void> deleteCustomTemplate(String id) async {
    await (_db.delete(_db.customTemplates)..where((t) => t.id.equals(id))).go();
  }
}

/// The custom-template store, named for the thing rather than the word
/// "provider" — matching `settingsStoreProvider` and
/// `personalDetailsStoreProvider`.
///
/// It reads [appDatabaseProvider], which is the seam a test overrides with an
/// in-memory database; there is no second database handle anywhere.
final customTemplateStoreProvider = Provider<CustomTemplateStore>(
  (ref) => CustomTemplateStore(ref.watch(appDatabaseProvider)),
);

/// Parent muscle group ids as the single column the table stores.
///
/// **The taxonomy order is applied here, on the way in.** The column's contract
/// is "comma-joined in taxonomy order", and a template's subtitle is derived by
/// joining those ids — so two templates naming the same groups must produce the
/// same string or they render differently for no reason the user can see.
/// Normalising on write rather than on read means the stored value is already
/// correct for anything that reads the column without going through
/// [decodeGroupIds].
///
/// Ids the taxonomy does not know are dropped, because taxonomy order is
/// undefined for them and a template cannot render a group that does not exist.
/// Repeats collapse for the same reason: the set of groups is what a template
/// is, and listing chest twice says nothing extra.
String encodeGroupIds(List<String> groupIds) {
  final wanted = groupIds.toSet();
  return <String>[
    for (final id in kMuscleTaxonomy.keys)
      if (wanted.contains(id)) id,
  ].join(',');
}

/// The parent group ids a stored column names.
///
/// **A plain split, because [encodeGroupIds] already did the work.** The empty
/// string is the case worth the method: `''.split(',')` yields `['']`, which
/// would hang a phantom group off every template that has none.
List<String> decodeGroupIds(String stored) {
  if (stored.isEmpty) return const <String>[];
  return stored.split(',');
}

/// One stored row as the template the rest of the app renders.
///
/// **[WorkoutTemplate.filters] is empty, and that is the whole rule about
/// custom templates.** They sit outside the split filter: `templatesFor` only
/// ever walks [kPredefinedTemplates], and the landing lists these separately
/// under their own heading whichever filter is showing. With no unfiltered
/// "All" value, classifying a custom template by muscle composition would leave
/// the user's own template reachable only from whichever bucket the classifier
/// picked.
///
/// **No subtitle is stored.** [WorkoutTemplate.subtitle] derives it from the
/// group ids, like every other display value in the app. The one predefined
/// template that overrides its subtitle does so because twelve joined labels
/// are too long a line; a custom template the user actually built is not going
/// to hit that.
///
/// [CustomTemplateRow.sourceTemplateId] deliberately does not come across.
/// [WorkoutTemplate] has nowhere to put it, and the only thing that wants it is
/// a "Duplicated from Push day" line on a template-editing screen that does not
/// exist yet. The column is written and read faithfully by the store; where it
/// surfaces is that screen's decision, not this function's.
WorkoutTemplate templateFromRow(CustomTemplateRow row) => WorkoutTemplate(
      id: row.id,
      name: row.name,
      groupIds: decodeGroupIds(row.groupIds),
      filters: const <TemplateFilter>{},
      isPredefined: false,
    );

/// The user's templates as the app started with them, resolved **before the
/// first frame**.
///
/// **This exists to be overridden, and `main()` is what overrides it** — the
/// same shape, and the same reasoning, as `initialTemplateFilterProvider` and
/// `initialBodyweightLogProvider`. An `AsyncNotifier` reading the table in
/// `build()` resolves a frame or more after the tree first builds, and the
/// Workout landing is the app's opening screen: the custom group would be
/// absent on the first frame and then appear, pushing the ad-hoc entry down
/// under the user's thumb. "Absent entirely" is a real state for a user with no
/// templates, which is exactly why showing it to a user who has some is not a
/// cosmetic glitch.
///
/// The default here — no templates — is what a test, or a missed override,
/// gets, and it is also the honest state of a fresh install.
final initialCustomTemplatesProvider = Provider<List<WorkoutTemplate>>(
  (ref) => const <WorkoutTemplate>[],
);

/// Reads the stored rows into templates, in the order the list renders.
///
/// Called once from `main()` before `runApp`. No fallback is needed: unlike a
/// filter key there is no vocabulary to fail to recognise, and an empty table
/// is the ordinary first-launch answer rather than an error.
Future<List<WorkoutTemplate>> readStoredCustomTemplates(
  CustomTemplateStore store,
) async {
  final rows = await store.readCustomTemplates();
  return rows.map(templateFromRow).toList(growable: false);
}

/// The templates the user built themselves, and the only way to change them.
///
/// **A `Notifier`, not an `AsyncNotifier`** — see [initialCustomTemplatesProvider]
/// for why the read happens before the tree builds rather than inside it. And
/// not a `StateProvider`, which is legacy on Riverpod 3 (see
/// `lib/src/ui/tab_index.dart`).
///
/// **Every mutation writes the database first and then the state**, matching
/// `BodyweightLog.record`. The state is not re-read from the table afterwards:
/// a round trip per keystroke-sized edit buys nothing, and the one fact that
/// would justify it — the order rows come back in — is stated once in
/// [CustomTemplateStore.readCustomTemplates] and reproduced here by
/// [_sorted]. If those two ever disagree the list reshuffles on restart, which
/// is what `test/custom_templates_test.dart` pins.
class CustomTemplateList extends Notifier<List<WorkoutTemplate>> {
  @override
  List<WorkoutTemplate> build() => ref.read(initialCustomTemplatesProvider);

  /// Saves a new template and returns it.
  ///
  /// **The id is minted here, not passed in.** It has to be stable across
  /// renames and unique across a list the user keeps adding to, and a caller
  /// that got to choose would sooner or later derive one from the name — which
  /// is the one thing about a template that changes.
  ///
  /// It is returned rather than kept to itself because the caller needs it
  /// immediately: the screen that saves a template is the screen that then
  /// renames or deletes it, and re-finding the row by name would be wrong the
  /// moment two templates share one.
  ///
  /// [sourceTemplateId] names the predefined template this was duplicated from,
  /// and is null for one built from scratch.
  Future<WorkoutTemplate> add({
    required String name,
    required List<String> groupIds,
    String? sourceTemplateId,
  }) async {
    final id = const Uuid().v4();
    await ref.read(customTemplateStoreProvider).insertCustomTemplate(
          id: id,
          name: name,
          groupIds: encodeGroupIds(groupIds),
          sourceTemplateId: sourceTemplateId,
        );

    // Built from the encoded ids rather than from the argument, so what the
    // caller gets back is what the next launch will read — a caller handing
    // over an unknown id or a duplicate must not see it survive in memory only.
    final saved = WorkoutTemplate(
      id: id,
      name: name,
      groupIds: decodeGroupIds(encodeGroupIds(groupIds)),
      filters: const <TemplateFilter>{},
      isPredefined: false,
    );
    state = _sorted(<WorkoutTemplate>[...state, saved]);
    return saved;
  }

  /// Renames the template with [id], leaving its groups alone. A stale id is a
  /// no-op in both the database and the list.
  Future<void> rename(String id, String name) async {
    await ref.read(customTemplateStoreProvider).renameCustomTemplate(id, name);

    state = _sorted(<WorkoutTemplate>[
      for (final template in state)
        if (template.id == id)
          WorkoutTemplate(
            id: template.id,
            name: name,
            groupIds: template.groupIds,
            filters: template.filters,
            isPredefined: template.isPredefined,
            subtitleOverride: template.subtitleOverride,
          )
        else
          template,
    ]);
  }

  /// Deletes the template with [id]. A stale id is a no-op in both the database
  /// and the list.
  Future<void> delete(String id) async {
    await ref.read(customTemplateStoreProvider).deleteCustomTemplate(id);
    state = <WorkoutTemplate>[
      for (final template in state)
        if (template.id != id) template,
    ];
  }

  /// The order [CustomTemplateStore.readCustomTemplates] returns: by name, then
  /// by id. Kept next to the writes that need it so the two orderings are read
  /// side by side when either changes.
  static List<WorkoutTemplate> _sorted(List<WorkoutTemplate> templates) {
    final ordered = <WorkoutTemplate>[...templates]..sort((a, b) {
        final byName = a.name.compareTo(b.name);
        return byName != 0 ? byName : a.id.compareTo(b.id);
      });
    return List<WorkoutTemplate>.unmodifiable(ordered);
  }
}

/// The user's templates, and the handle that changes them.
///
/// Named for the list rather than for "provider", matching `tabIndexProvider`
/// and `bodyweightLogProvider`. Read it through [customTemplatesProvider];
/// reach for `.notifier` only to add, rename or delete.
final customTemplateListProvider =
    NotifierProvider<CustomTemplateList, List<WorkoutTemplate>>(
  CustomTemplateList.new,
);

/// The templates the user built themselves, as the Workout landing reads them.
///
/// **A plain [Provider] in front of [customTemplateListProvider], and the
/// indirection is load-bearing.** This is the one provider the landing has ever
/// watched, and `test/workout_root_test.dart` injects its fixtures with
/// `customTemplatesProvider.overrideWithValue([...])`. Riverpod 3 offers
/// `overrideWithValue` on [Provider] and not on `NotifierProvider`, so
/// promoting this name to the notifier would force every widget test that only
/// wants "a user with one template" to stand up a database it has no interest
/// in. Splitting the read surface from the mutation surface keeps the cheap
/// override and costs one line.
///
/// **Overriding this detaches it from the notifier** — which is the point for a
/// rendering test, and a trap for a test that means to exercise a write. A test
/// that calls `add`, `rename` or `delete` must seed
/// [initialCustomTemplatesProvider] instead and leave this one alone, or it
/// will watch a constant while the notifier changes underneath it.
///
/// **Custom templates sit outside the split filter.** They are shown whichever
/// filter is selected. With no unfiltered "All" value, classifying them by
/// muscle composition would leave a user's own template reachable only from
/// whichever bucket the classifier picked, and an arbitrary catch-all would put
/// a single-muscle custom template under Multi Split while the predefined
/// equivalent sat under 1 Muscle per day.
final customTemplatesProvider = Provider<List<WorkoutTemplate>>(
  (ref) => ref.watch(customTemplateListProvider),
);
