#!/usr/bin/env python3
"""
exercise_library.py — source of truth for the V1 exercise library.

Schema per row:  (name, equipment, primary[], secondary[])
  primary   — muscles the exercise directly and heavily loads. Drives the
              `trained` tick and which sub-muscle-group list the exercise
              appears in. Max 3. Most exercises have exactly 1.
  secondary — meaningfully assisting muscles. Drives the light muscle-map
              fill only. Never ticks anything.

Muscle ids MUST match muscle_taxonomy.json. Validated by validate_exercise_library.py.
Content fields (setup / execution / commonMistake) are added in a later pass.
"""

LOAD_TYPES = ["weighted", "bodyweight", "assisted", "timed"]

EQUIPMENT = ["barbell", "dumbbell", "machine", "cable", "bodyweight",
             "kettlebell", "bands", "other"]

# name, equipment, loadType, primary, secondary
EXERCISES = [
# ---------------------------------------------------------------- CHEST / MID
("Barbell bench press", "barbell", "weighted", ["chest/mid"], ["chest/lower", "shoulders/front-delt", "triceps/triceps"]),
("Dumbbell bench press", "dumbbell", "weighted", ["chest/mid"], ["chest/lower", "shoulders/front-delt", "triceps/triceps"]),
("Machine chest press", "machine", "weighted", ["chest/mid"], ["shoulders/front-delt", "triceps/triceps"]),
("Smith machine bench press", "machine", "weighted", ["chest/mid"], ["shoulders/front-delt", "triceps/triceps"]),
("Push-up", "bodyweight", "bodyweight", ["chest/mid"], ["shoulders/front-delt", "triceps/triceps", "abs/upper"]),
("Wide-grip push-up", "bodyweight", "bodyweight", ["chest/mid"], ["shoulders/front-delt", "triceps/triceps"]),
("Cable chest press", "cable", "weighted", ["chest/mid"], ["shoulders/front-delt", "triceps/triceps"]),
("Pec deck machine", "machine", "weighted", ["chest/mid"], ["shoulders/front-delt"]),
("Dumbbell fly", "dumbbell", "weighted", ["chest/mid"], ["shoulders/front-delt"]),
("Cable crossover (mid pulley)", "cable", "weighted", ["chest/mid"], ["shoulders/front-delt"]),
("Barbell floor press", "barbell", "weighted", ["chest/mid"], ["triceps/triceps", "shoulders/front-delt"]),
("Dumbbell floor press", "dumbbell", "weighted", ["chest/mid"], ["triceps/triceps", "shoulders/front-delt"]),
("Kettlebell floor press", "kettlebell", "weighted", ["chest/mid"], ["triceps/triceps", "shoulders/front-delt"]),
("Resistance band chest press", "bands", "weighted", ["chest/mid"], ["shoulders/front-delt", "triceps/triceps"]),
("Plate press (Svend press)", "other", "weighted", ["chest/mid"], ["shoulders/front-delt"]),

# -------------------------------------------------------------- CHEST / UPPER
("Incline barbell bench press", "barbell", "weighted", ["chest/upper"], ["shoulders/front-delt", "triceps/triceps"]),
("Incline dumbbell press", "dumbbell", "weighted", ["chest/upper"], ["shoulders/front-delt", "triceps/triceps"]),
("Incline machine chest press", "machine", "weighted", ["chest/upper"], ["shoulders/front-delt", "triceps/triceps"]),
("Incline smith machine press", "machine", "weighted", ["chest/upper"], ["shoulders/front-delt", "triceps/triceps"]),
("Incline dumbbell fly", "dumbbell", "weighted", ["chest/upper"], ["shoulders/front-delt"]),
("Low-to-high cable crossover", "cable", "weighted", ["chest/upper"], ["shoulders/front-delt"]),
("Feet-elevated push-up", "bodyweight", "bodyweight", ["chest/upper"], ["shoulders/front-delt", "triceps/triceps"]),
("Incline cable press", "cable", "weighted", ["chest/upper"], ["shoulders/front-delt", "triceps/triceps"]),
("Reverse-grip bench press", "barbell", "weighted", ["chest/upper"], ["triceps/triceps", "shoulders/front-delt"]),
("Landmine press", "barbell", "weighted", ["chest/upper"], ["shoulders/front-delt", "triceps/triceps"]),
("Incline band press", "bands", "weighted", ["chest/upper"], ["shoulders/front-delt", "triceps/triceps"]),

# -------------------------------------------------------------- CHEST / LOWER
("Decline barbell bench press", "barbell", "weighted", ["chest/lower"], ["triceps/triceps", "shoulders/front-delt"]),
("Decline dumbbell press", "dumbbell", "weighted", ["chest/lower"], ["triceps/triceps", "shoulders/front-delt"]),
("Chest dip", "bodyweight", "bodyweight", ["chest/lower"], ["triceps/triceps", "shoulders/front-delt"]),
("Assisted chest dip machine", "machine", "assisted", ["chest/lower"], ["triceps/triceps", "shoulders/front-delt"]),
("High-to-low cable crossover", "cable", "weighted", ["chest/lower"], ["shoulders/front-delt"]),
("Decline machine press", "machine", "weighted", ["chest/lower"], ["triceps/triceps", "shoulders/front-delt"]),
("Hands-elevated push-up", "bodyweight", "bodyweight", ["chest/lower"], ["triceps/triceps", "shoulders/front-delt"]),
("Decline dumbbell fly", "dumbbell", "weighted", ["chest/lower"], ["shoulders/front-delt"]),
("Decline smith machine press", "machine", "weighted", ["chest/lower"], ["triceps/triceps"]),

# ---------------------------------------------------------------- BACK / LATS
("Pull-up", "bodyweight", "bodyweight", ["back/lats"], ["biceps/biceps", "back/upper", "forearms/forearms", "shoulders/rear-delt"]),
("Chin-up", "bodyweight", "bodyweight", ["back/lats"], ["biceps/biceps", "back/upper", "forearms/forearms"]),
("Assisted pull-up machine", "machine", "assisted", ["back/lats"], ["biceps/biceps", "back/upper", "forearms/forearms"]),
("Lat pulldown", "cable", "weighted", ["back/lats"], ["biceps/biceps", "back/upper", "forearms/forearms"]),
("Close-grip lat pulldown", "cable", "weighted", ["back/lats"], ["biceps/biceps", "back/upper", "forearms/forearms"]),
("Wide-grip lat pulldown", "cable", "weighted", ["back/lats"], ["biceps/biceps", "back/upper", "shoulders/rear-delt"]),
("Straight-arm pulldown", "cable", "weighted", ["back/lats"], ["triceps/triceps", "abs/upper"]),
("Barbell bent-over row", "barbell", "weighted", ["back/lats", "back/upper"], ["biceps/biceps", "shoulders/rear-delt", "back/lower", "forearms/forearms"]),
("Pendlay row", "barbell", "weighted", ["back/lats", "back/upper"], ["biceps/biceps", "shoulders/rear-delt", "back/lower"]),
("Single-arm dumbbell row", "dumbbell", "weighted", ["back/lats"], ["biceps/biceps", "back/upper", "shoulders/rear-delt", "forearms/forearms"]),
("Seated cable row", "cable", "weighted", ["back/lats", "back/upper"], ["biceps/biceps", "shoulders/rear-delt", "forearms/forearms"]),
("T-bar row", "barbell", "weighted", ["back/lats", "back/upper"], ["biceps/biceps", "shoulders/rear-delt", "back/lower"]),
("Chest-supported machine row", "machine", "weighted", ["back/lats", "back/upper"], ["biceps/biceps", "shoulders/rear-delt"]),
("Inverted row", "bodyweight", "bodyweight", ["back/lats", "back/upper"], ["biceps/biceps", "shoulders/rear-delt", "abs/upper"]),
("Dumbbell pullover", "dumbbell", "weighted", ["back/lats"], ["chest/mid", "triceps/triceps"]),
("Kettlebell row", "kettlebell", "weighted", ["back/lats"], ["biceps/biceps", "back/upper", "forearms/forearms"]),
("Resistance band lat pulldown", "bands", "weighted", ["back/lats"], ["biceps/biceps", "back/upper"]),
("Meadows row", "barbell", "weighted", ["back/lats"], ["biceps/biceps", "back/upper", "shoulders/rear-delt"]),
("Machine pullover", "machine", "weighted", ["back/lats"], ["triceps/triceps"]),

# --------------------------------------------------------------- BACK / UPPER
("Barbell shrug", "barbell", "weighted", ["back/upper"], ["forearms/forearms"]),
("Dumbbell shrug", "dumbbell", "weighted", ["back/upper"], ["forearms/forearms"]),
("Machine shrug", "machine", "weighted", ["back/upper"], ["forearms/forearms"]),
("Cable shrug", "cable", "weighted", ["back/upper"], ["forearms/forearms"]),
("Trap bar shrug", "barbell", "weighted", ["back/upper"], ["forearms/forearms"]),
("Kettlebell shrug", "kettlebell", "weighted", ["back/upper"], ["forearms/forearms"]),
("Face pull", "cable", "weighted", ["back/upper", "shoulders/rear-delt"], ["biceps/biceps"]),
("Barbell upright row", "barbell", "weighted", ["back/upper", "shoulders/side-delt"], ["biceps/biceps", "forearms/forearms"]),
("Dumbbell upright row", "dumbbell", "weighted", ["back/upper", "shoulders/side-delt"], ["biceps/biceps", "forearms/forearms"]),
("Cable upright row", "cable", "weighted", ["back/upper", "shoulders/side-delt"], ["biceps/biceps"]),
("Chest-supported dumbbell row", "dumbbell", "weighted", ["back/upper"], ["back/lats", "biceps/biceps", "shoulders/rear-delt"]),
("Seal row", "barbell", "weighted", ["back/upper"], ["back/lats", "biceps/biceps", "shoulders/rear-delt"]),
("Prone Y-raise", "dumbbell", "weighted", ["back/upper"], ["shoulders/rear-delt"]),
("Farmer's carry", "dumbbell", "timed", ["back/upper", "forearms/forearms"], ["abs/upper", "obliques/obliques"]),
("Band pull-apart", "bands", "weighted", ["back/upper", "shoulders/rear-delt"], []),

# --------------------------------------------------------------- BACK / LOWER
("Back extension", "bodyweight", "bodyweight", ["back/lower"], ["glutes/glutes", "hamstrings/hamstrings"]),
("Machine back extension", "machine", "bodyweight", ["back/lower"], ["glutes/glutes", "hamstrings/hamstrings"]),
("Conventional deadlift", "barbell", "weighted", ["back/lower", "hamstrings/hamstrings", "glutes/glutes"], ["back/upper", "back/lats", "quads/quads", "forearms/forearms"]),
("Trap bar deadlift", "barbell", "weighted", ["back/lower", "quads/quads", "glutes/glutes"], ["hamstrings/hamstrings", "back/upper", "forearms/forearms"]),
("Barbell good morning", "barbell", "weighted", ["back/lower", "hamstrings/hamstrings"], ["glutes/glutes"]),
("Rack pull", "barbell", "weighted", ["back/lower", "back/upper"], ["back/lats", "glutes/glutes", "forearms/forearms"]),
("Reverse hyperextension", "machine", "bodyweight", ["back/lower"], ["glutes/glutes", "hamstrings/hamstrings"]),
("Superman", "bodyweight", "bodyweight", ["back/lower"], ["glutes/glutes"]),
("Bird dog", "bodyweight", "bodyweight", ["back/lower"], ["glutes/glutes", "abs/upper"]),

# --------------------------------------------------------- SHOULDERS / FRONT
("Barbell overhead press", "barbell", "weighted", ["shoulders/front-delt"], ["shoulders/side-delt", "triceps/triceps", "back/upper", "abs/upper"]),
("Seated dumbbell shoulder press", "dumbbell", "weighted", ["shoulders/front-delt"], ["shoulders/side-delt", "triceps/triceps"]),
("Standing dumbbell shoulder press", "dumbbell", "weighted", ["shoulders/front-delt"], ["shoulders/side-delt", "triceps/triceps", "abs/upper"]),
("Machine shoulder press", "machine", "weighted", ["shoulders/front-delt"], ["shoulders/side-delt", "triceps/triceps"]),
("Smith machine shoulder press", "machine", "weighted", ["shoulders/front-delt"], ["shoulders/side-delt", "triceps/triceps"]),
("Arnold press", "dumbbell", "weighted", ["shoulders/front-delt"], ["shoulders/side-delt", "triceps/triceps"]),
("Push press", "barbell", "weighted", ["shoulders/front-delt"], ["shoulders/side-delt", "triceps/triceps", "quads/quads"]),
("Dumbbell front raise", "dumbbell", "weighted", ["shoulders/front-delt"], ["shoulders/side-delt"]),
("Barbell front raise", "barbell", "weighted", ["shoulders/front-delt"], ["shoulders/side-delt"]),
("Cable front raise", "cable", "weighted", ["shoulders/front-delt"], ["shoulders/side-delt"]),
("Plate front raise", "other", "weighted", ["shoulders/front-delt"], ["shoulders/side-delt"]),
("Landmine shoulder press", "barbell", "weighted", ["shoulders/front-delt"], ["triceps/triceps", "abs/upper"]),
("Pike push-up", "bodyweight", "bodyweight", ["shoulders/front-delt"], ["triceps/triceps", "shoulders/side-delt"]),
("Kettlebell overhead press", "kettlebell", "weighted", ["shoulders/front-delt"], ["triceps/triceps", "abs/upper"]),
("Band overhead press", "bands", "weighted", ["shoulders/front-delt"], ["triceps/triceps"]),

# ---------------------------------------------------------- SHOULDERS / SIDE
("Dumbbell lateral raise", "dumbbell", "weighted", ["shoulders/side-delt"], ["back/upper"]),
("Seated dumbbell lateral raise", "dumbbell", "weighted", ["shoulders/side-delt"], []),
("Cable lateral raise", "cable", "weighted", ["shoulders/side-delt"], ["back/upper"]),
("Leaning cable lateral raise", "cable", "weighted", ["shoulders/side-delt"], []),
("Machine lateral raise", "machine", "weighted", ["shoulders/side-delt"], []),
("Band lateral raise", "bands", "weighted", ["shoulders/side-delt"], []),
("Kettlebell lateral raise", "kettlebell", "weighted", ["shoulders/side-delt"], []),
("Plate lateral raise", "other", "weighted", ["shoulders/side-delt"], []),
("Lu raise", "dumbbell", "weighted", ["shoulders/side-delt"], ["back/upper", "shoulders/front-delt"]),
("Cable Y-raise", "cable", "weighted", ["shoulders/side-delt"], ["shoulders/front-delt", "back/upper"]),
("Barbell overhead carry", "barbell", "timed", ["shoulders/side-delt"], ["abs/upper", "back/upper"]),

# ---------------------------------------------------------- SHOULDERS / REAR
("Bent-over dumbbell reverse fly", "dumbbell", "weighted", ["shoulders/rear-delt"], ["back/upper"]),
("Chest-supported dumbbell reverse fly", "dumbbell", "weighted", ["shoulders/rear-delt"], ["back/upper"]),
("Reverse pec deck", "machine", "weighted", ["shoulders/rear-delt"], ["back/upper"]),
("Machine rear delt fly", "machine", "weighted", ["shoulders/rear-delt"], ["back/upper"]),
("Cable reverse fly", "cable", "weighted", ["shoulders/rear-delt"], ["back/upper"]),
("Reverse cable crossover", "cable", "weighted", ["shoulders/rear-delt"], ["back/upper"]),
("Rear delt cable row to neck", "cable", "weighted", ["shoulders/rear-delt"], ["back/upper", "biceps/biceps"]),
("Prone incline rear delt raise", "dumbbell", "weighted", ["shoulders/rear-delt"], ["back/upper"]),
("Band reverse fly", "bands", "weighted", ["shoulders/rear-delt"], ["back/upper"]),
("Kettlebell high pull", "kettlebell", "weighted", ["shoulders/rear-delt", "back/upper"], ["biceps/biceps"]),

# -------------------------------------------------------------------- BICEPS
("Barbell curl", "barbell", "weighted", ["biceps/biceps"], ["forearms/forearms"]),
("EZ-bar curl", "barbell", "weighted", ["biceps/biceps"], ["forearms/forearms"]),
("Dumbbell curl", "dumbbell", "weighted", ["biceps/biceps"], ["forearms/forearms"]),
("Alternating dumbbell curl", "dumbbell", "weighted", ["biceps/biceps"], ["forearms/forearms"]),
("Hammer curl", "dumbbell", "weighted", ["biceps/biceps", "forearms/forearms"], []),
("Incline dumbbell curl", "dumbbell", "weighted", ["biceps/biceps"], ["forearms/forearms"]),
("Concentration curl", "dumbbell", "weighted", ["biceps/biceps"], ["forearms/forearms"]),
("Spider curl", "dumbbell", "weighted", ["biceps/biceps"], ["forearms/forearms"]),
("Zottman curl", "dumbbell", "weighted", ["biceps/biceps", "forearms/forearms"], []),
("Preacher curl", "barbell", "weighted", ["biceps/biceps"], ["forearms/forearms"]),
("Machine preacher curl", "machine", "weighted", ["biceps/biceps"], ["forearms/forearms"]),
("Cable curl", "cable", "weighted", ["biceps/biceps"], ["forearms/forearms"]),
("Cable rope hammer curl", "cable", "weighted", ["biceps/biceps", "forearms/forearms"], []),
("Bayesian cable curl", "cable", "weighted", ["biceps/biceps"], ["forearms/forearms"]),
("Drag curl", "barbell", "weighted", ["biceps/biceps"], ["forearms/forearms"]),
("21s barbell curl", "barbell", "weighted", ["biceps/biceps"], ["forearms/forearms"]),
("Kettlebell curl", "kettlebell", "weighted", ["biceps/biceps"], ["forearms/forearms"]),
("Band curl", "bands", "weighted", ["biceps/biceps"], ["forearms/forearms"]),

# ------------------------------------------------------------------- TRICEPS
("Cable pushdown (straight bar)", "cable", "weighted", ["triceps/triceps"], []),
("Cable rope pushdown", "cable", "weighted", ["triceps/triceps"], []),
("Reverse-grip cable pushdown", "cable", "weighted", ["triceps/triceps"], []),
("Overhead cable triceps extension", "cable", "weighted", ["triceps/triceps"], []),
("Cable triceps kickback", "cable", "weighted", ["triceps/triceps"], []),
("EZ-bar skull crusher", "barbell", "weighted", ["triceps/triceps"], []),
("Close-grip bench press", "barbell", "weighted", ["triceps/triceps"], ["chest/mid", "shoulders/front-delt"]),
("JM press", "barbell", "weighted", ["triceps/triceps"], ["chest/mid"]),
("Dumbbell overhead triceps extension", "dumbbell", "weighted", ["triceps/triceps"], []),
("Single-arm dumbbell overhead extension", "dumbbell", "weighted", ["triceps/triceps"], []),
("Lying dumbbell triceps extension", "dumbbell", "weighted", ["triceps/triceps"], []),
("Dumbbell triceps kickback", "dumbbell", "weighted", ["triceps/triceps"], []),
("Machine triceps extension", "machine", "weighted", ["triceps/triceps"], []),
("Assisted triceps dip machine", "machine", "assisted", ["triceps/triceps"], ["chest/lower", "shoulders/front-delt"]),
("Bench triceps dip", "bodyweight", "bodyweight", ["triceps/triceps"], ["shoulders/front-delt", "chest/lower"]),
("Parallel bar dip (upright)", "bodyweight", "bodyweight", ["triceps/triceps"], ["chest/lower", "shoulders/front-delt"]),
("Diamond push-up", "bodyweight", "bodyweight", ["triceps/triceps"], ["chest/mid", "shoulders/front-delt"]),
("Kettlebell overhead extension", "kettlebell", "weighted", ["triceps/triceps"], []),
("Band triceps pushdown", "bands", "weighted", ["triceps/triceps"], []),

# ------------------------------------------------------------------ FOREARMS
("Barbell wrist curl", "barbell", "weighted", ["forearms/forearms"], []),
("Barbell reverse wrist curl", "barbell", "weighted", ["forearms/forearms"], []),
("Behind-the-back barbell wrist curl", "barbell", "weighted", ["forearms/forearms"], []),
("EZ-bar reverse curl", "barbell", "weighted", ["forearms/forearms"], ["biceps/biceps"]),
("Dumbbell wrist curl", "dumbbell", "weighted", ["forearms/forearms"], []),
("Dumbbell reverse wrist curl", "dumbbell", "weighted", ["forearms/forearms"], []),
("Cable wrist curl", "cable", "weighted", ["forearms/forearms"], []),
("Kettlebell farmer hold", "kettlebell", "timed", ["forearms/forearms"], ["back/upper"]),
("Dead hang", "bodyweight", "timed", ["forearms/forearms"], ["back/lats", "back/upper"]),
("Plate pinch hold", "other", "timed", ["forearms/forearms"], []),
("Wrist roller", "other", "timed", ["forearms/forearms"], []),
("Band wrist extension", "bands", "weighted", ["forearms/forearms"], []),
("Machine gripper", "machine", "weighted", ["forearms/forearms"], []),

# ----------------------------------------------------------------- ABS / UPPER
("Crunch", "bodyweight", "bodyweight", ["abs/upper"], []),
("Sit-up", "bodyweight", "bodyweight", ["abs/upper"], ["abs/lower"]),
("Decline sit-up", "bodyweight", "bodyweight", ["abs/upper"], ["abs/lower"]),
("Toe-touch crunch", "bodyweight", "bodyweight", ["abs/upper"], []),
("Plank", "bodyweight", "timed", ["abs/upper"], ["abs/lower", "obliques/obliques"]),
("V-up", "bodyweight", "bodyweight", ["abs/upper", "abs/lower"], []),
("Cable crunch", "cable", "weighted", ["abs/upper"], ["obliques/obliques"]),
("Machine crunch", "machine", "weighted", ["abs/upper"], []),
("Weighted dumbbell crunch", "dumbbell", "weighted", ["abs/upper"], []),
("Ab wheel rollout", "other", "bodyweight", ["abs/upper"], ["abs/lower", "back/lower"]),
("Stability ball crunch", "other", "bodyweight", ["abs/upper"], []),

# ----------------------------------------------------------------- ABS / LOWER
("Hanging leg raise", "bodyweight", "bodyweight", ["abs/lower"], ["forearms/forearms", "obliques/obliques"]),
("Hanging knee raise", "bodyweight", "bodyweight", ["abs/lower"], ["forearms/forearms"]),
("Captain's chair knee raise", "machine", "bodyweight", ["abs/lower"], []),
("Lying leg raise", "bodyweight", "bodyweight", ["abs/lower"], []),
("Reverse crunch", "bodyweight", "bodyweight", ["abs/lower"], []),
("Cable reverse crunch", "cable", "weighted", ["abs/lower"], []),
("Flutter kick", "bodyweight", "timed", ["abs/lower"], []),
("Scissor kick", "bodyweight", "timed", ["abs/lower"], []),
("Mountain climber", "bodyweight", "timed", ["abs/lower"], ["obliques/obliques", "shoulders/front-delt"]),
("Dead bug", "bodyweight", "bodyweight", ["abs/lower"], ["abs/upper"]),
("Dragon flag", "bodyweight", "bodyweight", ["abs/lower"], ["abs/upper"]),

# ------------------------------------------------------------------ OBLIQUES
("Russian twist", "bodyweight", "bodyweight", ["obliques/obliques"], ["abs/upper"]),
("Weighted Russian twist", "dumbbell", "weighted", ["obliques/obliques"], ["abs/upper"]),
("Side plank", "bodyweight", "timed", ["obliques/obliques"], ["abs/upper"]),
("Bicycle crunch", "bodyweight", "bodyweight", ["obliques/obliques"], ["abs/upper", "abs/lower"]),
("Hanging oblique knee raise", "bodyweight", "bodyweight", ["obliques/obliques"], ["abs/lower", "forearms/forearms"]),
("Cable woodchopper", "cable", "weighted", ["obliques/obliques"], ["abs/upper"]),
("Pallof press", "cable", "weighted", ["obliques/obliques"], ["abs/upper"]),
("Cable side bend", "cable", "weighted", ["obliques/obliques"], []),
("Dumbbell side bend", "dumbbell", "weighted", ["obliques/obliques"], []),
("Suitcase carry", "dumbbell", "timed", ["obliques/obliques"], ["forearms/forearms", "back/upper"]),
("Landmine rotation", "barbell", "weighted", ["obliques/obliques"], ["abs/upper", "shoulders/front-delt"]),
("Machine torso rotation", "machine", "weighted", ["obliques/obliques"], []),

# --------------------------------------------------------------------- QUADS
("Barbell back squat", "barbell", "weighted", ["quads/quads"], ["glutes/glutes", "hamstrings/hamstrings", "back/lower", "abs/upper"]),
("Barbell front squat", "barbell", "weighted", ["quads/quads"], ["glutes/glutes", "abs/upper", "back/upper"]),
("Box squat", "barbell", "weighted", ["quads/quads", "glutes/glutes"], ["hamstrings/hamstrings"]),
("Zercher squat", "barbell", "weighted", ["quads/quads"], ["glutes/glutes", "abs/upper", "back/upper"]),
("Landmine squat", "barbell", "weighted", ["quads/quads"], ["glutes/glutes", "abs/upper"]),
("Goblet squat", "dumbbell", "weighted", ["quads/quads"], ["glutes/glutes", "abs/upper"]),
("Kettlebell goblet squat", "kettlebell", "weighted", ["quads/quads"], ["glutes/glutes", "abs/upper"]),
("Leg press", "machine", "weighted", ["quads/quads"], ["glutes/glutes", "hamstrings/hamstrings"]),
("Hack squat machine", "machine", "weighted", ["quads/quads"], ["glutes/glutes"]),
("Smith machine squat", "machine", "weighted", ["quads/quads"], ["glutes/glutes"]),
("Belt squat", "machine", "weighted", ["quads/quads"], ["glutes/glutes"]),
("Leg extension", "machine", "weighted", ["quads/quads"], []),
("Bulgarian split squat", "dumbbell", "weighted", ["quads/quads", "glutes/glutes"], ["hamstrings/hamstrings"]),
("Split squat", "dumbbell", "weighted", ["quads/quads", "glutes/glutes"], []),
("Walking lunge", "dumbbell", "weighted", ["quads/quads", "glutes/glutes"], ["hamstrings/hamstrings", "calves/calves"]),
("Reverse lunge", "dumbbell", "weighted", ["quads/quads", "glutes/glutes"], ["hamstrings/hamstrings"]),
("Step-up", "dumbbell", "weighted", ["quads/quads", "glutes/glutes"], ["calves/calves"]),
("Bodyweight squat", "bodyweight", "bodyweight", ["quads/quads"], ["glutes/glutes"]),
("Pistol squat", "bodyweight", "bodyweight", ["quads/quads"], ["glutes/glutes", "abs/upper"]),
("Sissy squat", "bodyweight", "bodyweight", ["quads/quads"], []),
("Wall sit", "bodyweight", "timed", ["quads/quads"], []),
("Band squat", "bands", "weighted", ["quads/quads"], ["glutes/glutes"]),

# ---------------------------------------------------------------- HAMSTRINGS
("Lying leg curl", "machine", "weighted", ["hamstrings/hamstrings"], ["calves/calves"]),
("Seated leg curl", "machine", "weighted", ["hamstrings/hamstrings"], ["calves/calves"]),
("Standing leg curl", "machine", "weighted", ["hamstrings/hamstrings"], []),
("Glute-ham raise", "machine", "bodyweight", ["hamstrings/hamstrings"], ["glutes/glutes", "back/lower"]),
("Barbell Romanian deadlift", "barbell", "weighted", ["hamstrings/hamstrings"], ["glutes/glutes", "back/lower", "forearms/forearms"]),
("Stiff-leg deadlift", "barbell", "weighted", ["hamstrings/hamstrings"], ["glutes/glutes", "back/lower"]),
("Dumbbell Romanian deadlift", "dumbbell", "weighted", ["hamstrings/hamstrings"], ["glutes/glutes", "back/lower"]),
("Single-leg Romanian deadlift", "dumbbell", "weighted", ["hamstrings/hamstrings", "glutes/glutes"], ["back/lower"]),
("Kettlebell swing", "kettlebell", "weighted", ["hamstrings/hamstrings", "glutes/glutes"], ["back/lower", "abs/upper"]),
("Nordic hamstring curl", "bodyweight", "bodyweight", ["hamstrings/hamstrings"], ["glutes/glutes"]),
("Stability ball hamstring curl", "other", "bodyweight", ["hamstrings/hamstrings"], ["glutes/glutes"]),
("Band leg curl", "bands", "weighted", ["hamstrings/hamstrings"], []),

# -------------------------------------------------------------------- GLUTES
("Barbell hip thrust", "barbell", "weighted", ["glutes/glutes"], ["hamstrings/hamstrings"]),
("Sumo deadlift", "barbell", "weighted", ["glutes/glutes", "quads/quads"], ["hamstrings/hamstrings", "back/lower", "forearms/forearms"]),
("Machine hip thrust", "machine", "weighted", ["glutes/glutes"], ["hamstrings/hamstrings"]),
("Smith machine hip thrust", "machine", "weighted", ["glutes/glutes"], ["hamstrings/hamstrings"]),
("Machine glute kickback", "machine", "weighted", ["glutes/glutes"], ["hamstrings/hamstrings"]),
("Hip abduction machine", "machine", "weighted", ["glutes/glutes"], []),
("Cable glute kickback", "cable", "weighted", ["glutes/glutes"], ["hamstrings/hamstrings"]),
("Cable pull-through", "cable", "weighted", ["glutes/glutes"], ["hamstrings/hamstrings", "back/lower"]),
("Glute bridge", "bodyweight", "bodyweight", ["glutes/glutes"], ["hamstrings/hamstrings"]),
("Single-leg glute bridge", "bodyweight", "bodyweight", ["glutes/glutes"], ["hamstrings/hamstrings"]),
("Frog pump", "bodyweight", "bodyweight", ["glutes/glutes"], []),
("Donkey kick", "bodyweight", "bodyweight", ["glutes/glutes"], []),
("Fire hydrant", "bodyweight", "bodyweight", ["glutes/glutes"], []),
("Curtsy lunge", "dumbbell", "weighted", ["glutes/glutes"], ["quads/quads"]),
("Kettlebell sumo squat", "kettlebell", "weighted", ["glutes/glutes", "quads/quads"], []),
("Banded lateral walk", "bands", "weighted", ["glutes/glutes"], []),

# -------------------------------------------------------------------- CALVES
("Standing calf raise machine", "machine", "weighted", ["calves/calves"], []),
("Seated calf raise machine", "machine", "weighted", ["calves/calves"], []),
("Donkey calf raise", "machine", "weighted", ["calves/calves"], []),
("Leg press calf raise", "machine", "weighted", ["calves/calves"], []),
("Smith machine calf raise", "machine", "weighted", ["calves/calves"], []),
("Barbell standing calf raise", "barbell", "weighted", ["calves/calves"], []),
("Dumbbell standing calf raise", "dumbbell", "weighted", ["calves/calves"], []),
("Single-leg dumbbell calf raise", "dumbbell", "weighted", ["calves/calves"], []),
("Bodyweight calf raise", "bodyweight", "bodyweight", ["calves/calves"], []),
("Single-leg bodyweight calf raise", "bodyweight", "bodyweight", ["calves/calves"], []),
("Band calf raise", "bands", "weighted", ["calves/calves"], []),
("Jump rope", "other", "timed", ["calves/calves"], []),
]
